
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain grid)
    (:requirements :equality :typing)
    (:types
        place - object
        shape - object
        key - object
        object
    )

    (:constants
        
    )

    (:predicates
        (conn ?x1 - place ?x2 - place)
        (key-shape ?x1 - key ?x2 - shape)
        (lock-shape ?x1 - place ?x2 - shape)
        (at ?x1 - key ?x2 - place)
        (at-robot ?x1 - place)
        (locked ?x1 - place)
        (carrying ?x1 - key)
        (open ?x1 - place)
    )

    (:functions
        
    )

    

    
    (:action disconnect
     :parameters (?place1 - place ?place2 - place)
     :precondition (and (conn ?place1 ?place2) (conn ?place2 ?place1))
     :effect (and
        (not (conn ?place1 ?place2))
        (not (conn ?place2 ?place1)))
    )

)