
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain grid)
    (:requirements :typing :equality)
    (:types
        place - object
        shape - object
        key - object
        object
    )

    (:constants
        
    )

    (:predicates
        (conn ?x1 - place ?x2 - place)
        (key-shape ?x1 - key ?x2 - shape)
        (lock-shape ?x1 - place ?x2 - shape)
        (at ?x1 - key ?x2 - place)
        (at-robot ?x1 - place)
        (locked ?x1 - place)
        (carrying ?x1 - key)
        (open ?x1 - place)
    )

    (:functions
        
    )

    

    
    (:action unlock
     :parameters (?curpos - place ?lockpos - place ?key - key ?shape - shape)
     :precondition (and (conn ?curpos ?lockpos) (key-shape ?key ?shape) (lock-shape ?lockpos ?shape) (at-robot ?curpos) (locked ?lockpos) (carrying ?key))
     :effect (and
        (open ?lockpos)
        (not (locked ?lockpos)))
    )


    (:action move
     :parameters (?curpos - place ?nextpos - place)
     :precondition (and (at-robot ?curpos) (conn ?curpos ?nextpos) (open ?nextpos))
     :effect (and
        (at-robot ?nextpos)
        (not (at-robot ?curpos)))
    )


    (:action pickup
     :parameters (?curpos - place ?key - key)
     :precondition (and (at-robot ?curpos) (at ?key ?curpos))
     :effect (and
        (carrying ?key)
        (not (at ?key ?curpos)))
    )

)